
export const FETCH_STUDENTS_START = 'FETCH_STUDENTS_START';
export const FETCH_STUDENTS_SUCCESS = 'FETCH_STUDENTS_SUCCESS';
export const FETCH_STUDENTS_FAIL = 'FETCH_STUDENTS_FAIL';
export const SET_STUDENTS = 'SET_STUDENTS';
